POST http://localhost:3003/api/blogs/
Content-Type: application/json

{ 
   "title" : "I want to be a millionare",
   "author" : "Huy pe",
   "url" : "fanumtax.net",
   "likes" : 400 
}
### //vai lon sech this shit is absolutely retarded, you'll need to put content type next to your request or else it will not recognise the data input
GET http://localhost:3003/api/blogs/
###
DELETE http://localhost:3003/api/blogs/664ccc9c55fd90d59c856c36