POST http://localhost:3003/api/users
Content-Type: application/json

{ 
   "username": "ilovethiccgirl",
   "name": "huype",
   "password": "lmao"
}
### //vai lon sech this shit is absolutely retarded, you'll need to put content type next to your request or else it will not recognise the data input
GET http://localhost:3003/api/users/
###
GET http://localhost:3003/api/blogs/
###
DELETE http://localhost:3003/api/blogs/
Authorization: Bearer 
###
PUT http://localhost:3003/api/blogs/6662e4ee4de79e5d8ac15839
Content-Type: application/json

{ 
   "title": "First class tests",
   "author": "Robert C. Martin",
   "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
   "likes": 26,
   "userId": "6662004d8db90263a2f9b84c",
   "id": "6662e4ee4de79e5d8ac15839"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{ 
   "username": "ilovethiccgirl",
   "password": "lmao"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{ 
   "username": "mluukkai",
   "password": "mluukkai"
}
